In [1]:
#get the data ready

In [ ]:
import pandas as pd
heart_disease = pd.read_csv("heart.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [4]:
#create X (feature matrxix)
x = heart_disease.drop("target", axis=1)

#create Y (label)
y = heart_disease["target"]

In [3]:
#choose the tight model and hyperparamaters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
#we'll keep the default hyperparameters
import sklearn
sklearn.show_versions()

System:
    python: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]
executable: /home/francis/anaconda3/envs/myenv/bin/python
   machine: Linux-7.0.0-28-generic-x86_64-with-glibc2.43

Python dependencies:
      sklearn: 1.7.2
          pip: 26.0.1
   setuptools: 82.0.1
        numpy: 2.2.6
        scipy: 1.15.3
       Cython: None
       pandas: 2.3.3
   matplotlib: 3.10.0
       joblib: 1.5.3
threadpoolctl: 3.6.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libscipy_openblas
       filepath: /home/francis/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy.libs/libscipy_openblas64_-56d6093b.so
        version: 0.3.29
threading_layer: pthreads
   architecture: Haswell

       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libscipy_openblas
       filepath: /home/francis/anaconda3/envs/myenv/lib/python3.10/site-packages/scipy.libs/libscipy_openblas-68440149.so
        version: 0.3.28
threading_layer: pthreads
   architecture: Haswell

       user_api: openmp
   internal_api: openmp
    num_threads: 12
         prefix: libgomp
       filepath: /home/francis/anaconda3/envs/myenv/lib/python3.10/site-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
        version: None

In [15]:
#fit the model to the training data

from sklearn.model_selection import train_test_split    
x_train,x_test, y_train,y_test = train_test_split(x,y, test_size=0.2)
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
692,53,1,0,140,203,1,0,155,1,3.1,0,0,3
892,54,1,0,110,239,0,1,126,1,2.8,1,1,3
514,44,1,1,120,220,0,1,170,0,0.0,2,0,2
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2
827,57,1,2,128,229,0,0,150,0,0.4,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,53,0,2,128,216,0,0,115,0,0.0,2,0,0
579,58,1,0,146,218,0,1,105,0,2.0,1,1,3
429,47,1,2,108,243,0,1,152,0,0.0,2,0,2
136,55,0,1,132,342,0,1,166,0,1.2,2,0,2
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2

In [12]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [28]:
#make a prediction
import numpy as np

In [16]:
y_preds = clf.predict(x_test)
y_preds

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0])

In [17]:
y_test

397    0
282    1
179    0
125    1
509    0
      ..
325    1
566    1
382    0
807    1
331    0
Name: target, Length: 205, dtype: int64

In [18]:
#evaluate the model on training the dataset
clf.score(x_train, y_train)

1.0

In [19]:
clf.score(x_test,y_test)

1.0

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       103
           1       1.00      1.00      1.00       102

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

In [22]:
confusion_matrix(y_test, y_preds)

array([[103,   0],
       [  0, 102]])

In [23]:
accuracy_score(y_test, y_preds)

1.0

In [24]:
#improve the model
#try different types of estimators

np.random.seed(42)

for i in range(10,100, 10):
    print(f"try the model with {i} estimators....")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"MOdal accuracy on test set: {clf.score(x_test, y_test)*100:.2f}%")
    print()

try the model with 10 estimators....
MOdal accuracy on test set: 98.54%

try the model with 20 estimators....
MOdal accuracy on test set: 98.54%

try the model with 30 estimators....
MOdal accuracy on test set: 100.00%

try the model with 40 estimators....
MOdal accuracy on test set: 100.00%

try the model with 50 estimators....
MOdal accuracy on test set: 100.00%

try the model with 60 estimators....
MOdal accuracy on test set: 100.00%

try the model with 70 estimators....
MOdal accuracy on test set: 98.54%

try the model with 80 estimators....
MOdal accuracy on test set: 98.54%

try the model with 90 estimators....
MOdal accuracy on test set: 100.00%

In [25]:
#save the model and load it

import pickle
pickle.dump(clf, open("random_forest1.pkl", "wb"))

In [27]:
#laod the model

loaded_model = pickle.load(open("random_forest1.pkl","rb"))
loaded_model.score(x_test,y_test)

1.0